# Generated by Django 4.1 on 2023-12-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmptyRoomData",
            fields=[
                ("deposit", models.IntegerField(blank=True, null=True)),
                ("month", models.SmallIntegerField(blank=True, null=True)),
                ("criteria", models.CharField(max_length=10)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=20)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=20)),
                ("address", models.CharField(max_length=10)),
                ("when", models.CharField(blank=True, max_length=20, null=True)),
                ("area", models.CharField(max_length=10)),
                ("my_area", models.CharField(blank=True, max_length=10, null=True)),
                ("my_floor", models.CharField(blank=True, max_length=10, null=True)),
                ("total_floor", models.CharField(blank=True, max_length=10, null=True)),
                ("now", models.CharField(blank=True, max_length=20, null=True)),
                ("recommend", models.CharField(blank=True, max_length=50, null=True)),
                ("parking", models.CharField(blank=True, max_length=10, null=True)),
                ("usage", models.CharField(blank=True, max_length=20, null=True)),
                ("direction", models.CharField(max_length=20)),
                ("index", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "empty_room_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LikeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maemul_id",
                    models.ForeignKey(
                        db_column="maemul_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.emptyroomdata",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "like_data",
            },
        ),
    ]
