# Generated by Django 4.1 on 2023-12-28 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_emptyroomdata_likemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likemodel",
            old_name="maemul_id",
            new_name="maemul",
        ),
        migrations.RenameField(
            model_name="likemodel",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="likemodel",
            unique_together={("user", "maemul")},
        ),
    ]
