# Generated by Django 4.1 on 2023-12-28 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_rename_maemul_id_likemodel_maemul_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likemodel",
            name="maemul",
            field=models.ForeignKey(
                db_column="index",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.emptyroomdata",
            ),
        ),
        migrations.AlterField(
            model_name="likemodel",
            name="user",
            field=models.ForeignKey(
                db_column="username",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.usermodel",
            ),
        ),
    ]
