# Generated by Django 4.1 on 2023-12-28 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0006_alter_likemodel_maemul_alter_likemodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likemodel",
            name="maemul",
            field=models.ForeignKey(
                db_column="maemul_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.emptyroomdata",
            ),
        ),
        migrations.AlterField(
            model_name="likemodel",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.usermodel",
            ),
        ),
        migrations.AlterModelTable(
            name="likemodel",
            table=None,
        ),
    ]
