# Generated by Django 4.1 on 2023-12-28 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0007_alter_likemodel_maemul_alter_likemodel_user_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="likemodel",
            table="like_data",
        ),
    ]
