<<<<<<< HEAD
# Generated by Django 4.1 on 2023-12-22 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.1 on 2023-12-22 04:27

from django.db import migrations, models
>>>>>>> 4d7405cddb6dcaffccd1c11ac09d0e887020e819


class Migration(migrations.Migration):
    initial = True

<<<<<<< HEAD
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Views",
>>>>>>> 4d7405cddb6dcaffccd1c11ac09d0e887020e819
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("maemul_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "maemul_id")},
            },
=======
                ("views", models.PositiveIntegerField(default=0)),
            ],
>>>>>>> 4d7405cddb6dcaffccd1c11ac09d0e887020e819
        ),
    ]
