# Generated by Django 4.1 on 2023-12-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finalApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="views",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="views",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="views",
            name="maemul_id",
        ),
        migrations.RemoveField(
            model_name="views",
            name="user",
        ),
    ]
